### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by hamzeyto** [solkin/appteka-android#1]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by solkin** [comment]
Hi, @Hamzeto938 
Of course, I welcome any help in contribution and will gladly consider your PR.
You may use my e-mail for communication: inbox@tomclaw.com
