### ISSUE TITLE
Add app to favorite

### ISSUE THREAD

**Issue by x64x2** [solkin/appteka-android#23]
Implement this feature where apps can be downloaded later by adding app to favorite

**Comment by solkin** [comment]
Hi! This feature is already available! You can add app to your favorite and it will be available in your profile
![photo_2024-08-23 00 14 50](https://github.com/user-attachments/assets/cef98ad7-e0e0-44a7-a997-01cb26773d89)
![photo_2024-08-23 00 15 50](https://github.com/user-attachments/assets/96f639c9-edd3-4847-9cea-c81972844499)
