### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by Poussinou** [solkin/appteka-android#4]
Hi,

Since this app is now officially GNU GPLv3licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, that do not use Google Play nor anything else, except F-Droid.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by solkin** [comment]
Hi!
Of course, I consider placing AppSend to the F-Droid.
And it will be ok if someone else will publish AppSend to F-Droid.

**Comment by solkin** [comment]
Closing issue for now.

**Comment by IzzySoft** [comment]
@solkin it seems you include Flurry Analytics with your app. Afraid that would not be acceptable at F-Droid. Could you provide a build flavor that comes without that?

**Comment by solkin** [comment]
@IzzySoft It seems, I can totally remove Flurry in the nearest release due to small functionality and big size.

**Comment by IzzySoft** [comment]
Yes, please do so (and let me know when that release is out), so I can update the issue at F-Droid and it can be picked up to build!

**Comment by IzzySoft** [comment]
P.S.: and don't forget to [tag your releases](https://github.com/solkin/appsend-android/releases) 😉 That makes it easier for F-Droid to know which commit to build – and to detect updates when they're available.

**Comment by IzzySoft** [comment]
@solkin may I suggest to reopen this issue, as the problems discussed are still unsolved? There was no new release yet, there still are no tags, etc. Thanks. And while being on it: Are you still planning to solve them? Because else we've got to close the inclusion request on our end (disclosure: I'm one of the F-Droid maintainers).

**Comment by solkin** [comment]
@IzzySoft sorry for such delay. I'm working on application backend for now and client-side update is delaying. Application update will be prepared in a month, I think. And there Flurry will be removed from project.

**Comment by IzzySoft** [comment]
Thanks for the feedback, @solkin! Good to know. Still I'd suggest to leave this issue open until solved, so it can be found easier.

**Comment by solkin** [comment]
Okay, I'll reopen this issue until it will be solved.

**Comment by IzzySoft** [comment]
@solkin looks like you were able to get rid of Flurry, congrats! Any news on the tags?

**Comment by solkin** [comment]
@IzzySoft FlurryAnalytics already removed: https://github.com/solkin/appteka-android/commit/2c5bb43444c852a737eb857a20e9e082ed84fd01
For now, I'm preparing release with lots of changes.

**Comment by IzzySoft** [comment]
Great news that, thanks! Please update us here again when the release is ready (especially, when the tag is there), so we can help you getting it into the F-Droid catalog.

**Comment by solkin** [comment]
@IzzySoft Hi! Finally, release is ready!
https://github.com/solkin/appteka-android/releases/tag/v5.0

**Comment by IzzySoft** [comment]
Thanks Igor! I've just prepared its metadata, so it should show up in my repo with tomorrow's sync [here](https://apt.izzysoft.de/fdroid/index/apk/com.tomclaw.appsend). Note it doesn't qualify for f-droid.org due to Hockey (F-Droid doesn't permit proprietary services). Also for privacy reasons, you might consider a "fully f/loss build flavor". Hockey is known to be one of the more invasive trackers. Otherwise I had offered you to help with a listing there (which I still do if you have such a flavor)…

If you need a "compliant" analytics package, e.g. [ACRA](/ACRA/acra) would qualify.

PS: just wondering if Sberbank really qualifies as your homepage? Are you really THE owner? Don't get me wrong, it's not meant as critics but an honest question (because of the corresponding metadata field, `AuthorWebsite`). If the answer is yes: molodez, and I'll shut up immediately :wink:

**Comment by vdbhb59** [comment]
@IzzySoft Maybe I am wrong, but he stores modded apps and pro version, pirated apps probably on his store (LuckyPatcher, UTorrent Pro, etc). If you open his webpage (https://appteka.store/) and his telegram chat you will know. Sharing few snaps and details here.
![857421663_283930](https://user-images.githubusercontent.com/60728004/75052932-6b78fa80-54f6-11ea-9bf0-7619c5011e27.jpg)
![500001800168_37204](https://user-images.githubusercontent.com/60728004/75052973-7fbcf780-54f6-11ea-887a-8d3e004f8eda.jpg)
http://t.me/appsend_store
Owner: https://t.me/zibuhoker
Hybrid analysis of the latest apk as per his website..
https://www.hybrid-analysis.com/sample/4e1eb1d085871f2fb363f6e7670f0388d2ed89a1d7b44edb113095c962c03948/5e4ffd6146c06c1e0e31ff75

One more thing.. His site IP is registered in [UK](https://iplookup.flagfox.net/?ip=178.62.103.5&host=appteka.store), his keystore is signed in Moscow.. Maybe this point is nothing, but just thought of sharing in case.

Do not report or block me "owner" like Nekogram developer did when confronted about him stealing user data and app filled with analytics. I am just another person trying to show if anything is wrong and not against anyone in particular. :+1:

**Comment by vdbhb59** [comment]
![Screenshot_20200222-001935](https://user-images.githubusercontent.com/60728004/75062705-5bb6e180-5509-11ea-8363-3e0b938c1b5d.jpg)
![Screenshot_20200222-002031](https://user-images.githubusercontent.com/60728004/75062713-5eb1d200-5509-11ea-8848-96df6fb13622.jpg)
Few more snaps showing pro apps, LP installer available on the app. I installed via FDroid just to take snaps. Also, Izzy one still shows: Can track and report one's activities..

**Comment by IzzySoft** [comment]
Thanks for sharing, @vdbhb59 – maybe that should be at least pointed out somehow in the description. @solkin would you suggest some disclaimer? Could you explain the content in a few words? As @vdbhb59 pointed out: no blaming here, we're just seeking clarification.

**Comment by vdbhb59** [comment]
> Thanks for sharing, @vdbhb59 – maybe that should be at least pointed out somehow in the description. @solkin would you suggest some disclaimer? Could you explain the content in a few words? As @vdbhb59 pointed out: no blaming here, we're just seeking clarification.

Welcome. True, just trying to seek clarification. The only reason I mentioned with snaps is, Nekogram developer keeps blocking anyone who seeks or asks. They keep deleting issues as well, the moment people raise it. Seeing how @solkin has been easy on speaking openly, so good on that part. :)

**Comment by solkin** [comment]
@IzzySoft @ vdbhb59
It's not a secret, that Appteka is an alternative apps store. Users can freely exchange with apps. There is some moderators, that trying to check uploads for issues and malware.
Before uploading, every user accept this disclaimer:
> Important! By clicking "Yes" you confirm that:
> 1. You do not violate the licenses of applications uploaded to the Appteka store.
> 2. This software does not violate copyright and applicable laws.
> 3. The owner of the appsend.store is not responsible for the uploaded software.

Before downloading, every user accepts another disclaimer:
> Submitted applications in this cloud are uploaded by Appteka users. The author is not responsible for the quality of the content provided. By clicking "Yes" you accept this condition.

I have no resources and wishes to moderate every program. It's just cloud for Android apps exchange, like any forum, but more user-friendly.

If you think it's not appliable for F-Droid - no problems, just remove it.
Maybe, you interest in AppSend https://github.com/solkin/appsend-android - this is Android apps management tool, a "father" of Appteka. This topic was started when Appteka was called AppSend and has no lots of cloud functionality.

**Comment by John3** [comment]
@solkin is right, is just an alternative apps store like aptoide, aptoide is already in fdroid store, with the same situation, if appteka meets the fdroid criteria should be included and maybe add a disclaimer or something in the description.

**Comment by solkin** [comment]
@IzzySoft can you please update Appteka 6.0 release?
Current release on F-Droid: https://apt.izzysoft.de/fdroid/index/apk/com.tomclaw.appsend
New release: https://github.com/solkin/appteka-android/releases/tag/v6.0

**Comment by IzzySoft** [comment]
It's set to auto-update, but I've triggered it manually now as due to no releases for more than a year it's on a weekly check instead of the usual daily one, and hence would only be due to be checked again next Sunday night – so you missed the last check by a few hours only :wink: Should you expect more frequent releases, I can put it back to the daily check, just let me know then.

PS: before you ask, v6.0 will show up with the next sync around 19:00 UTC today. Thanks for the note!

**Comment by solkin** [comment]
@IzzySoft Thank you for reply! I think, there is no need in daily checking. But as I see, app is not updated in F-Droid yet https://apt.izzysoft.de/fdroid/index/apk/com.tomclaw.appsend

**Comment by IzzySoft** [comment]
Funny. When I follow the link, it says it was updated yesterday to version 6.0. Do I miss something? v6.0 is also what your latest tag here says. When did you look? About an hour before your last comment here? Then you might have been minutes too early. Database updates a few minutes past 19:00 UTC; the index itself is usually updated around 18:45 UTC.

**Comment by solkin** [comment]
@IzzySoft Thanks, for now, application is updated.

**Comment by Deerp1976** [comment]
@solkin please see this report regarding an app on your app store called Vmos Pro on Virus Total which has 10 malicious reports out of 59 scanned. I have spoken to @IzzySoft about this and posted the Virus Total report on one of his Gitlab issue links - https://www.virustotal.com/gui/file/4a15c3c2eb70aa31ec1e1ffd34d9625c17399465196d4fa1b45904b3ed363a1a/details

https://gitlab.com/IzzyOnDroid/repo/-/issues/235#note_832961408

https://appteka.store/app/c19r52975

**Comment by IzzySoft** [comment]
Might be a good idea to have uploads scanned by VT automatically, and quarantine APKs if there are e.g. 5 or more hits (or at least show the number of hits with the app description). It's not that difficult (I'm doing that for my repo), and there are [multiple libraries available](https://support.virustotal.com/hc/en-us/articles/360006819798-API-Scripts-and-client-libraries) for integration. You will need one supporting v3 (as v2 is limited to 32M per file in the free version); my own library ([php-virustotal](https://codeberg.org/izzy/php-virustotal)) is v2 but uses v3 for just that part, in case PHP is an option for you.

**Comment by solkin** [comment]
@IzzySoft I have an idea to add automatic virus checking on backend. My backend is not PHP, it is GoLang microservice architecture in Docker containers. So, I am planning to add ClamAV or another AV software in Docker container for checking uploaded apk files for issues.

**Comment by IzzySoft** [comment]
The page I linked to has 3 Go libraries for VT (API 2.0, so a 32MB size limit for uploads with the free tier) and [one for API 3.0](https://github.com/VirusTotal/vt-go) (no such size limit). Using VT would bring you about 60 AV/malware engines at once. Exodus has an API interface as well if you wish to check for trackers.
